(() => {
 const $=id=>document.getElementById(id),form=$('bookForm'),overview=$('bookOverview');let db,records=[],currentId=null,photos=[],photoUrls=[],listUrls=[],busy=false,revision=0;
 const message=(id,text,error=false)=>{$(id).textContent=text;$(id).classList.toggle('error',error);};
 const changed=()=>{revision++;message('bookSaveMessage','Pense à enregistrer tes changements.');};
 const localDate=date=>new Date(date).toLocaleDateString('fr-FR');
 function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('eclat-kids-reading',1);r.onupgradeneeded=()=>r.result.createObjectStore('books',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Storage blocked'));});}
 function readBooks(){return new Promise((resolve,reject)=>{const r=db.transaction('books').objectStore('books').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 function writeBook(record){return new Promise((resolve,reject)=>{const t=db.transaction('books','readwrite');t.objectStore('books').put(record);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
 function showOverview(){form.hidden=true;overview.hidden=false;$('newBook').focus();}
 function renderBooks(){listUrls.forEach(url=>URL.revokeObjectURL(url));listUrls=[];const list=$('savedBooks');list.replaceChildren();records.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).forEach(record=>{const card=document.createElement('article');card.className='form-card child-book';const title=document.createElement('h3');title.textContent=record.title;const author=document.createElement('p');author.textContent=record.author;const stars=document.createElement('p');stars.textContent=record.rating?'★'.repeat(record.rating)+' · '+record.rating+'/5':'Pas encore de note';stars.setAttribute('aria-label',record.rating?record.rating+' étoiles sur 5':'Pas encore de note');const comment=document.createElement('p');comment.textContent=record.comment;const meta=document.createElement('p');meta.className='field-hint';meta.textContent='Dans ton carnet depuis le '+localDate(record.createdAt);const edit=document.createElement('button');edit.type='button';edit.className='photo-button';edit.textContent='Ouvrir mon livre';edit.setAttribute('aria-label','Ouvrir '+record.title);edit.addEventListener('click',()=>openBook(record));const copy=document.createElement('div');copy.className='child-book-copy';copy.append(title,author,stars,comment,meta);const first=record.photos?.[0];if(first?.blob){const img=document.createElement('img');img.className='child-book-photo';img.alt='Photo du livre '+record.title;img.src=URL.createObjectURL(first.blob);listUrls.push(img.src);card.append(img);card.classList.add('with-photo');}card.append(copy,edit);list.append(card);});}
 function openBook(record){if(busy)return;currentId=record?.id||crypto.randomUUID();form.reset();for(const [id,key]of [['bookTitle','title'],['bookAuthor','author'],['bookComment','comment']])$(id).value=record?.[key]||'';if(record?.rating)form.querySelector('input[name=rating][value="'+record.rating+'"]').checked=true;photos=Array.isArray(record?.photos)?record.photos.slice():[];renderPhotos();for(const id of ['photoMessage','bookSaveMessage'])message(id,'');$('bookHeading').textContent=record?'Mon livre':'Mon nouveau livre';overview.hidden=true;form.hidden=false;$('bookHeading').focus();}
 function renderPhotos(){photoUrls.forEach(url=>URL.revokeObjectURL(url));photoUrls=[];$('bookPhotos').replaceChildren();photos.forEach((photo,index)=>{const card=document.createElement('figure');card.className='photo-card';const img=document.createElement('img');img.src=URL.createObjectURL(photo.blob);photoUrls.push(img.src);img.alt='Photo '+(index+1)+' de mon livre';const caption=document.createElement('figcaption');caption.textContent=index===0?'Photo du carnet':'Photo '+(index+1);const controls=document.createElement('div');const cover=document.createElement('button');cover.type='button';cover.textContent='Illustrer la ligne';cover.disabled=index===0;cover.addEventListener('click',()=>{if(busy)return;photos.splice(index,1);photos.unshift(photo);renderPhotos();changed();});const remove=document.createElement('button');remove.type='button';remove.textContent='Retirer';remove.setAttribute('aria-label','Retirer la photo '+(index+1));remove.addEventListener('click',()=>{if(busy)return;photos=photos.filter(p=>p.id!==photo.id);renderPhotos();changed();$('choosePhotos').focus();});controls.append(cover,remove);card.append(img,caption,controls);$('bookPhotos').append(card);});}
 async function preparePhoto(file){if(!file.type.startsWith('image/'))throw new Error('Image required');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=url;});const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Conversion failed')),'image/jpeg',.85));return {id:crypto.randomUUID(),blob,originalName:file.name};}finally{URL.revokeObjectURL(url);}}
 function photoControls(enabled){for(const id of ['takePhoto','choosePhotos','cameraPhoto','galleryPhotos'])$(id).disabled=!enabled;}
 async function addPhotos(event){if(busy)return;const files=Array.from(event.target.files);if(!files.length)return;busy=true;$('saveBook').disabled=true;photoControls(false);message('photoMessage','Préparation des photos…');let added=0,failed=0;try{for(const file of files){try{photos.push(await preparePhoto(file));added++;}catch{failed++;}}renderPhotos();if(added)changed();message('photoMessage',failed?'Certaines photos n’ont pas pu être ouvertes. Essaie une image JPEG ou PNG.':added+' photo'+(added>1?'s ajoutées.':' ajoutée.'),failed>0);}finally{event.target.value='';busy=false;$('saveBook').disabled=!db;photoControls(!!db);}}
 $('takePhoto').addEventListener('click',()=>$('cameraPhoto').click());$('choosePhotos').addEventListener('click',()=>$('galleryPhotos').click());$('cameraPhoto').addEventListener('change',addPhotos);$('galleryPhotos').addEventListener('change',addPhotos);photoControls(false);
 $('newBook').addEventListener('click',()=>openBook(null));$('cancelBook').addEventListener('click',()=>{if(!busy)showOverview();});
 form.querySelectorAll('input:not([type=file]),textarea').forEach(node=>node.addEventListener('input',changed));
 form.addEventListener('submit',async event=>{event.preventDefault();if(!db||busy)return;busy=true;$('saveBook').disabled=true;photoControls(false);const savedRevision=revision,previous=records.find(r=>r.id===currentId),rating=Number(form.querySelector('input[name=rating]:checked')?.value||0);const record={...previous,id:currentId,version:3,createdAt:previous?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),title:$('bookTitle').value.trim(),author:$('bookAuthor').value.trim(),rating,comment:$('bookComment').value.trim(),photos:photos.slice()};if(!record.title||!record.author){busy=false;$('saveBook').disabled=false;photoControls(true);return;}try{await writeBook(record);const index=records.findIndex(r=>r.id===record.id);if(index<0)records.push(record);else records[index]=record;renderBooks();if(revision===savedRevision){showOverview();message('overviewMessage','Ton livre est enregistré !');}else message('bookSaveMessage','Pense à enregistrer tes derniers changements.');}catch{message('bookSaveMessage','Ton carnet n’a pas pu être enregistré. Demande de l’aide à un adulte.',true);}finally{busy=false;$('saveBook').disabled=false;photoControls(true);}});
 (async()=>{try{db=await database();records=await readBooks();renderBooks();$('newBook').disabled=false;$('saveBook').disabled=false;photoControls(true);message('overviewMessage',records.length?'':'Ton premier livre t’attend. Ajoute-le à ton carnet !');}catch{message('overviewMessage','Ton carnet ne peut pas être enregistré dans ce navigateur.',true);}})();
})();
