(() => {
 const $=id=>document.getElementById(id),form=$('bookForm'),overview=$('bookOverview');let db,records=[],currentId=null,quiz=null,source='',edition='',quizAvailable=false,busy=false,revision=0,stream=null,scanTimer=null,scanVersion=0;
 const message=(id,text,error=false)=>{$(id).textContent=text;$(id).classList.toggle('error',error);};
 const changed=()=>{revision++;message('bookSaveMessage','Pense à enregistrer tes changements.');};
 const localDate=date=>new Date(date).toLocaleDateString('fr-FR');
 function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('eclat-kids-reading',1);r.onupgradeneeded=()=>r.result.createObjectStore('books',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Storage blocked'));});}
 function readBooks(){return new Promise((resolve,reject)=>{const r=db.transaction('books').objectStore('books').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 function writeBook(record){return new Promise((resolve,reject)=>{const t=db.transaction('books','readwrite');t.objectStore('books').put(record);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
 function stopScanner(){scanVersion++;clearTimeout(scanTimer);if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;$('scanVideo').srcObject=null;$('scanVideo').hidden=true;$('stopScan').hidden=true;$('startScan').disabled=false;}
 function showOverview(){stopScanner();form.hidden=true;overview.hidden=false;$('newBook').focus();}
 function renderBooks(){const list=$('savedBooks');list.replaceChildren();records.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).forEach(record=>{const card=document.createElement('article');card.className='form-card child-book';const title=document.createElement('h3');title.textContent=record.title;const author=document.createElement('p');author.textContent=record.author;const stars=document.createElement('p');stars.textContent=record.rating?'★'.repeat(record.rating)+' · '+record.rating+'/5':'Pas encore de note';stars.setAttribute('aria-label',record.rating?record.rating+' étoiles sur 5':'Pas encore de note');const comment=document.createElement('p');comment.textContent=record.comment;const meta=document.createElement('p');meta.className='field-hint';meta.textContent='Dans ton carnet depuis le '+localDate(record.createdAt)+(record.quiz?' · '+record.quiz.questions.length+' questions':'');const edit=document.createElement('button');edit.type='button';edit.className='photo-button';edit.textContent='Ouvrir mon livre';edit.setAttribute('aria-label','Ouvrir '+record.title);edit.addEventListener('click',()=>openBook(record));card.append(title,author,stars,comment,meta,edit);list.append(card);});}
 function showResult(){if(!quiz)return;const result=EclatKidsQuiz.score(quiz.questions,quiz.answers);if(!result.complete){message('quizMessage','Choisis une réponse pour chaque question, puis découvre ton résultat.');return;}quiz.result=result;const panel=$('quizResult');panel.replaceChildren();const symbol=document.createElement('div');symbol.className='success-symbol';symbol.textContent='🎉';symbol.setAttribute('aria-hidden','true');const title=document.createElement('h3');title.textContent='Bravo pour ta lecture !';const text=document.createElement('p');text.textContent='Tu as exploré ton livre jusqu’au bout. Chaque question te fait découvrir quelque chose !';const score=document.createElement('p');score.textContent=result.correct+' bonne'+(result.correct>1?'s':'')+' réponse'+(result.correct>1?'s':'')+' sur '+result.total;panel.append(symbol,title,text,score);panel.hidden=false;quiz.questions.forEach((q,i)=>{const correction=document.getElementById('correction-'+i);correction.textContent='À retenir : '+q.choices[q.correctIndex];});changed();}
 function renderQuiz(){const container=$('quizQuestions');container.replaceChildren();$('finishQuiz').hidden=!quiz;$('quizResult').hidden=true;if(!quiz)return;quiz.questions.forEach((q,i)=>{const box=document.createElement('fieldset');box.className='quiz-question';const legend=document.createElement('legend');legend.textContent=(i+1)+'. '+q.question;box.append(legend);q.choices.forEach((choice,j)=>{const label=document.createElement('label');label.className='quiz-choice';const radio=document.createElement('input');radio.type='radio';radio.name='question-'+i;radio.value=String(j);radio.checked=quiz.answers?.[i]===j;radio.addEventListener('change',()=>{quiz.answers[i]=j;quiz.result=null;$('quizResult').hidden=true;container.querySelectorAll('.quiz-correction').forEach(node=>node.textContent='');changed();});const text=document.createElement('span');text.textContent=choice;label.append(radio,text);box.append(label);});const correction=document.createElement('p');correction.id='correction-'+i;correction.className='quiz-correction';box.append(correction);container.append(box);});const note=document.createElement('p');note.className='field-hint';note.textContent='Questions préparées par IA à partir du résumé. Pense à enregistrer tes réponses dans ton carnet.';container.append(note);if(quiz.result)showResult();}
 $('finishQuiz').addEventListener('click',showResult);
 function openBook(record){if(busy)return;stopScanner();currentId=record?.id||crypto.randomUUID();form.reset();for(const [id,key]of [['isbn','isbn'],['bookTitle','title'],['bookAuthor','author'],['bookComment','comment'],['storyContext','context']])$(id).value=record?.[key]||'';if(record?.rating)form.querySelector('input[name=rating][value="'+record.rating+'"]').checked=true;source=record?.source||'';edition=record?.edition||'';$('bookSource').textContent=source?'Fiche retrouvée dans Open Library'+(edition?' · édition '+edition:'')+'. Vérifie le titre et l’auteur.':'';quiz=record?.quiz?structuredClone(record.quiz):null;if(quiz){$('questionCount').value=quiz.questions.length;}renderQuiz();for(const id of ['lookupMessage','quizMessage','bookSaveMessage'])message(id,'');$('bookHeading').textContent=record?'Mon livre':'Mon nouveau livre';overview.hidden=true;form.hidden=false;$('bookHeading').focus();}
 async function lookup(){if(busy)return;stopScanner();const code=$('isbn').value.trim();if(!code){message('lookupMessage','Écris le numéro sous le code-barres.',true);return;}busy=true;$('findBook').disabled=true;message('lookupMessage','Je cherche ton livre…');try{const r=await fetch('/api/livres/isbn/'+encodeURIComponent(code));const data=await r.json();if(!r.ok)throw new Error(data.error);$('isbn').value=data.isbn;$('bookTitle').value=data.title;$('bookAuthor').value=data.author;source=data.source;edition=data.edition;$('bookSource').textContent='Fiche retrouvée dans Open Library'+(edition?' · édition '+edition:'')+'. Vérifie le titre et l’auteur.';quiz=null;renderQuiz();changed();message('lookupMessage',data.author?'Livre retrouvé ! Vérifie que c’est bien le tien.':'Titre retrouvé ! Ajoute l’auteur de ta couverture.');}catch(e){message('lookupMessage',e.message||'Livre non retrouvé. Tu peux remplir le titre et l’auteur.',true);}finally{busy=false;$('findBook').disabled=false;}}
 $('startScan').addEventListener('click',async()=>{if(busy)return;stopScanner();if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){message('lookupMessage','Le scan n’est pas disponible dans ce navigateur. Écris le numéro ISBN sous le code-barres.',true);return;}const version=scanVersion;$('startScan').disabled=true;try{const formats=(await BarcodeDetector.getSupportedFormats()).filter(v=>['ean_13','ean_8','upc_a'].includes(v));if(!formats.length)throw new Error('Scanner unavailable');const detector=new BarcodeDetector({formats});const camera=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(version!==scanVersion){camera.getTracks().forEach(t=>t.stop());return;}stream=camera;$('scanVideo').srcObject=stream;$('scanVideo').hidden=false;$('stopScan').hidden=false;await $('scanVideo').play();message('lookupMessage','Place le code-barres au centre de la caméra.');async function scan(){if(version!==scanVersion)return;try{const found=await detector.detect($('scanVideo'));const code=found.map(item=>item.rawValue).find(v=>/^97[89]\d{10}$/.test(v));if(code){$('isbn').value=code;stopScanner();await lookup();return;}}catch{}if(version===scanVersion)scanTimer=setTimeout(scan,300);}scan();}catch{stopScanner();message('lookupMessage','La caméra ne peut pas scanner ici. Tu peux saisir le numéro ISBN.',true);}});
 $('stopScan').addEventListener('click',stopScanner);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopScanner();});window.addEventListener('pagehide',stopScanner);$('findBook').addEventListener('click',lookup);
 $('newBook').addEventListener('click',()=>openBook(null));$('cancelBook').addEventListener('click',()=>{if(!busy)showOverview();});
 form.querySelectorAll('input,select,textarea').forEach(node=>node.addEventListener('input',()=>{changed();if(['bookTitle','bookAuthor','isbn'].includes(node.id)){source='';edition='';$('bookSource').textContent='';}}));
 $('generateQuiz').addEventListener('click',async()=>{if(busy||!quizAvailable)return;const title=$('bookTitle').value.trim(),author=$('bookAuthor').value.trim(),context=$('storyContext').value.trim(),count=Number($('questionCount').value);if(!title||!author||context.length<80||!Number.isInteger(count)||count<1||count>30){message('quizMessage','Ajoute le titre, l’auteur, un résumé d’au moins 80 caractères et choisis de 1 à 30 questions.',true);return;}stopScanner();busy=true;$('generateQuiz').disabled=true;message('quizMessage','Tes questions se préparent…');try{const r=await fetch('/api/enfants/questionnaire',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,author,context,count})});const data=await r.json();if(!r.ok)throw new Error(data.error);quiz={...data,answers:Array(data.questions.length).fill(-1)};renderQuiz();changed();message('quizMessage','Tes '+data.questions.length+' questions sont prêtes !');}catch(e){message('quizMessage',e.message||'Les questions n’ont pas pu être préparées.',true);}finally{busy=false;$('generateQuiz').disabled=!quizAvailable;}});
 form.addEventListener('submit',async event=>{event.preventDefault();if(!db||busy)return;busy=true;$('saveBook').disabled=true;stopScanner();const savedRevision=revision,previous=records.find(r=>r.id===currentId),rating=Number(form.querySelector('input[name=rating]:checked')?.value||0);const record={id:currentId,version:1,createdAt:previous?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),isbn:$('isbn').value.trim(),title:$('bookTitle').value.trim(),author:$('bookAuthor').value.trim(),rating,comment:$('bookComment').value.trim(),context:$('storyContext').value.trim(),source,edition,quiz:quiz?structuredClone(quiz):null};if(!record.title||!record.author){busy=false;$('saveBook').disabled=false;return;}try{await writeBook(record);const index=records.findIndex(r=>r.id===record.id);if(index<0)records.push(record);else records[index]=record;renderBooks();if(revision===savedRevision){showOverview();message('overviewMessage','Ton livre est enregistré !');}else message('bookSaveMessage','Pense à enregistrer tes derniers changements.');}catch{message('bookSaveMessage','Ton carnet n’a pas pu être enregistré. Demande de l’aide à un adulte.',true);}finally{busy=false;$('saveBook').disabled=false;}});
 (async()=>{try{db=await database();records=await readBooks();renderBooks();$('newBook').disabled=false;$('saveBook').disabled=false;message('overviewMessage',records.length?'':'Ton premier livre t’attend. Ajoute-le à ton carnet !');}catch{message('overviewMessage','Ton carnet ne peut pas être enregistré dans ce navigateur.',true);}try{const r=await fetch('/api/enfants/config');const data=await r.json();quizAvailable=!!data.quizAvailable;$('generateQuiz').disabled=!quizAvailable;$('quizAvailability').textContent=quizAvailable?'Choisis le nombre de questions. Elles utilisent des mots simples et parlent de l’histoire et des personnages.':'Les questionnaires IA ne sont pas encore activés. Tu peux déjà garder tes livres, tes étoiles et tes commentaires.';}catch{$('quizAvailability').textContent='Les questionnaires IA sont momentanément indisponibles.';}})();
})();
