const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function client(mode='ok'){
 const calls=[];let options;
 const fetch=async(url,opt={})=>{calls.push({url,opt});if(url==='/api/google-calendar/config')return {ok:true,json:async()=>({enabled:true,clientId:'123.apps.googleusercontent.com'})};if(url.includes('/userinfo'))return {ok:true,json:async()=>({email:mode==='wrong'?'other@example.org':'reader@example.org',verified_email:true})};if(opt.method==='GET')return mode==='linked'?{ok:true,status:200,json:async()=>({extendedProperties:{private:{eclatLoanId:'loan'}}})}:{ok:false,status:404};return {ok:true,status:opt.method==='DELETE'?204:200,json:async()=>({id:'event'})};};
 const window={EclatLoanCalendar:require('./library-loans-calendar')};const context={window,fetch,crypto:crypto.webcrypto,TextEncoder,Date,Intl,AbortSignal,document:{createElement:()=>({}),head:{append:s=>s.onload()}},google:{accounts:{oauth2:{hasGrantedAllScopes:()=>true,initTokenClient:o=>{options=o;return {requestAccessToken:()=>mode==='cancel'?o.error_callback():o.callback({access_token:'test-token'})};}}}}};
 vm.runInNewContext(fs.readFileSync('library-loans-google.js','utf8'),context);return {api:window.EclatLoanGoogle,calls,options:()=>options};
}
const record={id:'loan',returnDate:'2026-11-04',reminder:{enabled:true,date:'2026-11-04',time:'09:00'}};
test('creates personal weekly event with an explicit alert and no persisted token',async()=>{const c=client();await c.api.ready;const link=await c.api.save(record);assert.equal(link.ownerEmail,'reader@example.org');assert.equal(link.eventId,'event');const post=c.calls.find(c=>c.opt.method==='POST');const body=JSON.parse(post.opt.body);assert.deepEqual(body.recurrence,['RRULE:FREQ=WEEKLY']);assert.deepEqual(body.reminders,{useDefault:false,overrides:[{method:'popup',minutes:0}]});assert.match(body.id,/^ec[0-9a-f]{64}$/);assert.ok(c.options().scope.includes('calendar.events.owned'));assert.ok(!JSON.stringify(link).includes('test-token'));});
test('stops only the linked series belonging to this loan',async()=>{const c=client('linked');await c.api.ready;await c.api.remove({...record,googleCalendar:{eventId:'event',ownerEmail:'reader@example.org'}});assert.equal(c.calls.filter(c=>c.opt.method==='DELETE').length,1);});
test('denied authorization and a different Google account do not write events',async()=>{for(const mode of ['cancel','wrong']){const c=client(mode);await c.api.ready;await assert.rejects(c.api.save({...record,googleCalendar:{eventId:'event',ownerEmail:'reader@example.org'}}));assert.equal(c.calls.filter(c=>['POST','PATCH','DELETE'].includes(c.opt.method)).length,0);}});
