(function(root){
 const stores=[{db:'eclat-library-loans',store:'notebooks'},{db:'eclat-kids-reading',store:'books'}];
 const validKey=k=>/^eclat[-_]/i.test(k)&&!/^eclat_libraries_/i.test(k);
 async function encode(value){
  if(value instanceof Blob)return {__eclatBlob:true,type:value.type,data:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(value);})};
  if(Array.isArray(value))return Promise.all(value.map(encode));
  if(value&&typeof value==='object')return Object.fromEntries(await Promise.all(Object.entries(value).map(async([k,v])=>[k,await encode(v)])));
  return value;
 }
 function decode(value){
  if(value?.__eclatBlob===true){if(typeof value.data!=='string'||!/^data:[^,]*;base64,/.test(value.data))throw new Error('Photo invalide');const str=atob(value.data.slice(value.data.indexOf(',')+1));return new Blob([Uint8Array.from(str,c=>c.charCodeAt(0))],{type:typeof value.type==='string'?value.type:'application/octet-stream'});}
  if(Array.isArray(value))return value.map(decode);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,decode(v)]));
  return value;
 }
 function merge(a,b){if(Array.isArray(a)&&Array.isArray(b))return [...new Map([...b,...a].map(v=>[JSON.stringify(v),v])).values()];if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b))return Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(k=>[k,k in a&&k in b?merge(a[k],b[k]):k in b?b[k]:a[k]]));if(typeof a==='number'&&typeof b==='number')return Math.max(a,b);return b;}
 function validate(value){if(!value||value.application!=='Eclat'||value.version!==1||!value.localStorage||!Array.isArray(value.databases))throw new Error('Ce fichier ne contient pas une sauvegarde Éclat reconnue.');for(const [k,v] of Object.entries(value.localStorage))if(!validKey(k)||typeof v!=='string')throw new Error('Préférence invalide');for(const item of value.databases){if(!stores.some(s=>s.db===item.db&&s.store===item.store)||!Array.isArray(item.records)||item.records.length>10000)throw new Error('Carnet invalide');for(const r of item.records)if(!r||typeof r.id!=='string'||r.id.length>300)throw new Error('Entrée de carnet invalide');}return value;}
 function open(spec){return new Promise((resolve,reject)=>{const r=indexedDB.open(spec.db,1);r.onupgradeneeded=()=>r.result.createObjectStore(spec.store,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Fermez les autres pages Éclat, puis réessayez.'));});}
 function read(db,store){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly');const r=tx.objectStore(store).getAll();let result;r.onsuccess=()=>{result=r.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 async function exportData(){const local={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(validKey(k))local[k]=localStorage.getItem(k);}const databases=[];for(const spec of stores){const db=await open(spec);try{databases.push({...spec,records:await encode(await read(db,spec.store))});}finally{db.close();}}return {application:'Eclat',version:1,exportedAt:new Date().toISOString(),origin:location.origin,localStorage:local,databases};}
 async function importData(value){validate(value);const decoded=value.databases.map(item=>({...item,records:decode(item.records)}));let imported=0,preserved=0;
  for(const item of decoded){const db=await open(item);try{const existing=await read(db,item.store),byId=new Map(existing.map(r=>[r.id,r]));const inserts=item.records.filter(r=>{const old=byId.get(r.id);if(old&&String(old.updatedAt||old.createdAt||'')>=String(r.updatedAt||r.createdAt||'')){preserved++;return false;}imported++;return true;});if(inserts.length)await new Promise((resolve,reject)=>{const tx=db.transaction(item.store,'readwrite');for(const r of inserts)tx.objectStore(item.store).put(r);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
  for(const [k,v] of Object.entries(value.localStorage)){const current=localStorage.getItem(k);if(current===null)localStorage.setItem(k,v);else try{localStorage.setItem(k,JSON.stringify(merge(JSON.parse(v),JSON.parse(current))));}catch{/* Keep an existing value that cannot be merged. */}}
  return {imported,preserved};
 }
 root.EclatTransfer={encode,decode,merge,validate,exportData,importData};
 if(typeof document==='undefined')return;
 const status=document.getElementById('transferStatus'),download=document.getElementById('exportData'),input=document.getElementById('importData'),result=document.getElementById('backupSummary'),confirm=document.getElementById('confirmImport');let pending=null;
 function busy(value){download.disabled=value;input.disabled=value;confirm.disabled=value;}
 download.addEventListener('click',async()=>{busy(true);status.textContent='Préparation de la sauvegarde avec les photos…';try{const backup=await exportData(),blob=new Blob([JSON.stringify(backup)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='eclat-sauvegarde-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='Sauvegarde téléchargée. Elle contient vos carnets, photos, favoris et historique de cet appareil. Rien n’a été effacé.';}catch{status.textContent='La sauvegarde n’a pas pu être préparée. Gardez cette adresse et réessayez avant le transfert.';}finally{busy(false);confirm.disabled=!pending;}});
 input.addEventListener('change',async()=>{pending=null;confirm.disabled=true;result.textContent='';try{const file=input.files[0];if(!file)return;if(file.size>150*1024*1024)throw new Error('Ce fichier dépasse 150 Mo.');pending=validate(JSON.parse(await file.text()));result.textContent=pending.databases.reduce((n,d)=>n+d.records.length,0)+' entrées de carnets et '+Object.keys(pending.localStorage).length+' préférences/historiques prêts à importer. Les données déjà présentes seront conservées ou fusionnées.';confirm.disabled=false;}catch(e){status.textContent=e.message||'Le fichier ne peut pas être lu.';}});
 confirm.addEventListener('click',async()=>{if(!pending)return;busy(true);status.textContent='Import en cours…';try{const r=await importData(pending);status.textContent=r.imported+' entrées importées, '+r.preserved+' entrées déjà présentes conservées. Vous pouvez revenir à l’accueil.';pending=null;}catch{status.textContent='L’import n’a pas pu être terminé. Rien n’a été effacé ; gardez la sauvegarde et réessayez.';}finally{busy(false);confirm.disabled=!pending;}});
})(typeof window!=='undefined'?window:globalThis);
